trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  acr: 'moto1acr.azurecr.io'

steps:
- task: Docker@1
  displayName: 'docker build'
  inputs:
    azureSubscriptionEndpoint: python
    azureContainerRegistry: $(acr)
    dockerFile: Dockerfile

- task: Docker@1
  displayName: 'docker push'
  inputs:
   azureSubscriptionEndpoint: python
   azureContainerRegistry: $(acr)
   command: Push an image

- task: AzureWebAppContainer@1
  displayName: 'web app'
  inputs:
    azureSubscription: python
    appName: 'testing-python-app'
    containers: 'moto1acr.azurecr.io/pythonproject:$(Build.BuildID)'

